### ISSUE TITLE
Hover color fix

### ISSUE THREAD

**Issue by neilerdwien** [neilerdwien/homepage-2017#14]
The blue hover must be coming from Bootstrap.

**Comment by jcorkill** [comment]
I'm not seeing any hover colors - and the link text is black in the Events and News areas.

**Comment by neilerdwien** [comment]
I must have accidentally fixed it.  At one time, the purple links, like on the Admissions and the campuses layers, turned blue on hover/focus.

But I don't see it either, so I'll close the ticket.
