### ISSUE TITLE
Implement the advisories layer

### ISSUE THREAD

**Issue by neilerdwien** [neilerdwien/homepage-2017#15]

**Comment by jcorkill** [comment]
I saw the implementation... can we update the style to be more layer-ish? Ex attached...
![advisories-example](https://cloud.githubusercontent.com/assets/27312145/24975905/fade2b3e-1f8c-11e7-80e5-d49b5f2a4c26.jpg)

**Comment by neilerdwien** [comment]
How about now?

**Comment by jcorkill** [comment]
Looks great!!
