### ISSUE TITLE
catch up with social media icons

### ISSUE THREAD

**Issue by neilerdwien** [neilerdwien/homepage-2017#21]
We've got several that are old and obsolete.

**Comment by jcorkill** [comment]
Michelle wants to remove Foursquare and add Instagram icons to the footer. And we need to update that Twitter icon. I can push it over to Ashley/design when we get the icons from Michelle.

**Comment by jcorkill** [comment]
Submitted the file update to Ashley, but I assume the coding change could happen and the file can just follow (the icon order shouldn't change).

**Comment by jcorkill** [comment]
Uploaded the updated social-media.png with the new instagram image.

**Comment by neilerdwien** [comment]
Done.
