### ISSUE TITLE
Events and News text need hover underline/color

### ISSUE THREAD

**Issue by jcorkill** [neilerdwien/homepage-2017#36]

**Comment by neilerdwien** [comment]
...and the links inside the 2025/Innovation layer.

**Comment by neilerdwien** [comment]
No bottom border normally.  Standard purple bottom border on hover.  Text changes to purple too.

**Comment by neilerdwien** [comment]
I did this with a standard hover.  Which, I realized, is what the footer was already doing and the menu does courtesy of Bootstrap.

But is it now too much?  The Admissions and Campuses layers, in particular.

**Comment by neilerdwien** [comment]
Oh, and a purple bottom border just looked silly on gray text.  :-)

**Comment by jcorkill** [comment]
I'm not a fan of the really heavy underline on Campuses, Engagement and Strategic layers. The Admissions layer is a lot... but not horrible.

**Comment by neilerdwien** [comment]
That is the rock.  And the hard place is that we have no control over the thickness of the underline.  It should be possible to have a bottom border on the larger text items and still leave the standard underline on other items.  But adding that would be three levels of override and probably needs some bigger thought.
