### ISSUE TITLE
Opacity on Engagement layer?

### ISSUE THREAD

**Issue by jcorkill** [neilerdwien/homepage-2017#37]
I think the text on the Engagement layer is a little hard to read. Is there opacity on the background image that can be adjusted?

**Comment by neilerdwien** [comment]
I don't think there is a way to adjust the opacity of a background image without affecting the content of the containing element, i.e., the text. 

But the fix is simple: adjust the image itself.  For that matter, wasn't a replacement image for that layer in progress?

**Comment by jcorkill** [comment]
I lightened the background image just a tinge. I applied a little gradient to the lower left pulling it up over the far left of Anderson. It helps a bit... Interesting to see if we get comments about it.
