### ISSUE TITLE
Implement the Instagram layer

### ISSUE THREAD

**Issue by neilerdwien** [neilerdwien/homepage-2017#5]

**Comment by neilerdwien** [comment]
Questions:
Can we add such a layer given we're not supposed to endorse a specific business?
My reading of the API says we can only do between 500 and 5000 views/hour.  I think the homepage will be more than that.  Going to the 5000/hr limit requires Instagram approve our application.  They say they won't do that for "website widgets".  But, we could ask.

Perhaps Tagboard or Juicer would be better?

**Comment by jcorkill** [comment]
In general, I would assert that the name of the layer shouldn't be "Instagram" or another specific business. Should ask Ashley for a marketing title :-)

**Comment by neilerdwien** [comment]
I think this is done with a Tagboard for CaptureKState.
