### ISSUE TITLE
gap between menu and its dropdown

### ISSUE THREAD

**Issue by neilerdwien** [neilerdwien/homepage-2017#54]
Moving the dropdown box lower to make it line up with the top of the banner made there be a small gap between the trigger and the dropdown.  If you move the mouse quickly, you can still make it into the menu before it closes.  But if move slowly, it'll close.

**Comment by jcorkill** [comment]
Yeah, this is a problem. I can move fairly quickly and it still closes before I get down to it. :-(

**Comment by neilerdwien** [comment]
Fixed, although the fix makes me a little nervous.  I removed padding from the overall nav bar, but added it back in to each nav item.  I'm worried I'm messing up some balance Bootstrap has designed.  The narrow screen view is spaced out now -- but it might be OK.  If it isn't, we'll open a new ticket.  So much for "mobile first".  :-)

**Comment by jcorkill** [comment]
It definitely works better now!!
